// SPDX-License-Identifier: MIT
import type { LucideIcon } from "lucide-react";
import {
  Activity,
  BarChart3,
  Bell,
  BriefcaseBusiness,
  CalendarDays,
  Clock,
  Database,
  FileImage,
  FileText,
  Flag,
  Folder,
  Globe,
  HelpCircle,
  Image,
  Info,
  Languages,
  LayoutDashboard,
  Mail,
  MapPin,
  Newspaper,
  Package2,
  Palette,
  Scale,
  Search,
  Settings2,
  Share2,
  ShieldCheck,
  Sparkles,
  Store,
  Tag,
  Trash2,
  Users,
  Wrench,
} from "lucide-react";
import type { AdminNavIconComponent, AdminNavIconName, AdminNavItem } from "../adapters";

const iconMap: Record<AdminNavIconName, LucideIcon> = {
  activity: Activity,
  article: Newspaper,
  bell: Bell,
  briefcase: BriefcaseBusiness,
  calendar: CalendarDays,
  chart: BarChart3,
  clock: Clock,
  database: Database,
  file: FileText,
  flag: Flag,
  folder: Folder,
  globe: Globe,
  help: HelpCircle,
  image: Image,
  info: Info,
  language: Languages,
  mail: Mail,
  map: MapPin,
  media: FileImage,
  overview: LayoutDashboard,
  palette: Palette,
  product: Package2,
  scale: Scale,
  search: Search,
  settings: Settings2,
  share: Share2,
  shield: ShieldCheck,
  sparkles: Sparkles,
  store: Store,
  tag: Tag,
  trash: Trash2,
  users: Users,
  wrench: Wrench,
};

export function resolveNavIcon(icon: AdminNavItem["icon"]): AdminNavIconComponent | null {
  if (!icon) {
    return null;
  }
  return typeof icon === "string" ? iconMap[icon] : icon;
}
